window.areasC = TAFFY(
    [{
        id: 1,
        name: "CASOS CLÍNICOS INTERATIVOS I",
    }, {
        id: 2,
        name: "CIÊNCIA BÁSICA",
    }, {
        id: 3,
        name: "DOENÇA INFLAMATÓRIA INTESTINAL I",
    }, {
        id: 4,
        name: "ENDOSCOPIA DIGESTIVA I",
    }, {
        id: 5,
        name: "FÍGADO I",
    }, {
        id: 6,
        name: "NSTANTÂNEOS/VÍDEOS I",
    }, {
        id: 7,
        name: "PÂNCREAS E VIAS BILIARES",
    }, {
        id: 8,
        name: "SESSÃO PLENÁRIA",
    }, {
        id: 9,
        name: "TUBO DIGESTIVO I",
    }, ]);
window.projectX = TAFFY(
    [{
        id: 1,
        date: 5,
        areaC: 8,
        title: "REMISSÃO ENDOSCÓPICA E HISTOLÓGICA INDUZIDA PELO INFLIXIMAB NA COLITE ULCEROSA MODERADA A GRAVE – ESTUDO HÉRICA",
        authors: "Magro F., Lopes S., Lopes J., Rodrigues-Pinto E., Portela F., Silva M., Cotter J., João Moreira M., Lago P., Lopes C., Caetano C., Peixe P. , Chagas C., Carvalho L., Lopes S., Rosa B., Albuquerque A., Camila C., Afonso J., Geboes K., Carneiro F.",
        url: "src/docs/760.pdf",
    }, {
        id: 2,
        date: 5,
        areaC: 8,
        title: "ADMINISTRAÇÃO DE PROPOFOL POR NÃO ANESTESISTA (NAAP) EM COLONOSCOPIA – ANÁLISE INTERINA DE UM ENSAIO CONTROLADO E ALEATORIZADO",
        authors: "Ferreira AO, Torres J, Pinto R, Schuler V, Castanheira C, Neves M, Santos AS, Silva F, Cravo M",
        url: "src/docs/785.pdf",
    }, {
        id: 3,
        date: 5,
        areaC: 8,
        title: "SEGUIMENTO A LONGO PRAZO APÓS EXÉRESE POR MUCOSECTOMIA (EMR) OU POR DISSECÇÃO (ESD) DE LESÕES SUPERFICIAIS GÁSTRICAS EM PORTUGAL",
        authors: "Pimentel-Nunes P, Mourão F, Veloso N, Afonso LP, Jácome J, Moreira-Dias L, Dinis-Ribeiro M",
        url: "src/docs/472.pdf",
    }, {
        id: 4,
        date: 5,
        areaC: 8,
        title: "MIRNAS DO MÚSCULO ESQUELÉTICO EM DOENTES COM FÍGADO GORDO NÃO ALCOÓLICO E SUA MODULAÇÃO IN VITRO",
        authors: "Simão A.L., Ferreira D.M.S., Borralho P.M., Machado M.V., Cortez-Pinto H., Rodrigues C.M.P., Castro R.E.",
        url: "src/docs/707.pdf",
    }, {
        id: 5,
        date: 5,
        areaC: 8,
        title: "TRATAMENTO ENDOSCÓPICO DE FUGAS BILIARES: DO PLÁSTICO AO METAL DESDE O TRATAMENTO INICIAL ATÉ À NECESSIDADE DE REVISÃO ENDOSCÓPICA NAS FUGAS REFRACTÁRIAS",
        authors: "Russo P, Canena J, Horta D, Coimbra J, Meireles L , Marques I, Ricardo L, Rodrigues C, Capela T, Carvalho D, Loureiro R, Dias AM, Ramos G, Coutinho AP, Romão C",
        url: "src/docs/670.pdf",
    }, {
        id: 6,
        date: 5,
        areaC: 8,
        title: "O IMPACTO DA INFECÇÃO PELO VÍRUS DA HEPATITE C EM DOENTES SUBMETIDOS A TRANSPLANTAÇÃO RENAL",
        authors: "Magalhães-Costa P., Lebre L., Machado D., Chagas C.",
        url: "src/docs/498.pdf",
    }, {
        id: 7,
        date: 5,
        areaC: 8,
        title: "FACTORES DE RISCO PARA FOCOS DE CRIPTAS ABERRANTES NA COLITE ULCEROSA",
        authors: "Freire P., Figueiredo P., Cardoso R., Donato M.M., Ferreira M., Mendes S., Cipriano M.A., Silva M.R., Ferreira A.M., Vasconcelos H., Portela F., Sofia C.",
        url: "src/docs/621.pdf",
    }, {
        id: 8,
        date: 5,
        areaC: 8,
        title: "UTILIDADE DA ENDOSCOPIA POR CÁPSULA NA ORIENTAÇÃO TERAPÊUTICA DE DOENTES COM DOENÇA DE CROHN",
        authors: "Santos-Antunes J, , Cardoso H, , Marques M, , Magro F, , Nunes ACR, , Lopes S, , Macedo G.",
        url: "src/docs/689.pdf",
    }, {
        id: 9,
        date: 5,
        areaC: 5,
        title: "OS NOVOS DOENTES COM HEPATITE C: CARACTERIZAÇÃO DEMOGRÁFICA, VIROLÓGICA E ESTÁDIO DE DOENÇA DOS REFERENCIADOS “DE NOVO” A UMA CONSULTA HOSPITALAR ",
        authors: "Russo P., Costa M.N., Silva M.J., Côrte-Real R., Calinas F.",
        url: "src/docs/840.pdf",
    }, {
        id: 10,
        date: 5,
        areaC: 5,
        title: "SÍNDROME HEPATOPULMONAR EM CRIANÇAS CANDIDATAS A TRANSPLANTE HEPÁTICO",
        authors: "Joana Amaral, Susana Nobre, Maristela Margatho, Sandra Ferreira, Isabel Gonçalves, Emanuel Furtado",
        url: "src/docs/997.pdf",
    }, {
        id: 11,
        date: 5,
        areaC: 5,
        title: "EVOLUÇÃO DOS INTERNAMENTOS HOSPITALARES POR CIRROSE HEPÁTICA E SUAS COMPLICAÇÕES EM PORTUGAL ENTRE 2003 E 2012",
        authors: "Silva M.J., Costa M.N., Rosa M., Nogueira P., Esteves J., Calinas F.",
        url: "src/docs/991.pdf",
    }, {
        id: 12,
        date: 5,
        areaC: 5,
        title: "PAPEL DA QUANTIFICAÇÃO DO AGHBS NA IDENTIFICAÇÃO PRECOCE DE PORTADORES INACTIVOS DO VÍRUS DA HEPATITE B",
        authors: "Silva M.J., Costa M.N., Russo P., Côrte-Real R., Calinas F.",
        url: "src/docs/915.pdf",
    }, {
        id: 13,
        date: 5,
        areaC: 5,
        title: "POSTOPERATIVE RESOURCE UTILIZATION AND SURVIVAL AMONG LIVER TRANSPLANT RECIPIENTS WITH A MELD SCORE GREATER THAN OR EQUAL TO 40: A RETROSPECTIVE COHORT STUDY",
        authors: "Filipe S. Cardoso, Constantine J. Karvellas, Norman Kneteman, Glenda Meeberg , Pedro Fidalgo , Sean M. Bagshaw",
        url: "src/docs/452.pdf",
    }, {
        id: 14,
        date: 5,
        areaC: 5,
        title: "TERMOABLAÇÃO POR MICRO-ONDAS OU RADIOFREQUÊNCIA NA ABORDAGEM DAS NEOPLASIAS MALIGNAS HEPÁTICAS?",
        authors: "Oliveira A., , Campos S., Giestas S., Almeida N., Casela A., Souto P., Gomes D., Agostinho A. G., Alves F. Sofia C.",
        url: "src/docs/706.pdf",
    }, {
        id: 15,
        date: 5,
        areaC: 3,
        title: "MANIFESTAÇÕES OTORRINOLARINGOLÓGICAS NA DOENÇA INFLAMATÓRIA INTESTINAL – ESTUDO PILOTO",
        authors: "Oliveira A., Ribeiro J. C., Freire P., Ferreira M., Portela F., Sofia C.",
        url: "src/docs/698.pdf",
    }, {
        id: 16,
        date: 5,
        areaC: 3,
        title: "ISQUEMIA SILENCIOSA DO MIOCÁRDIO NA DOENÇA INFLAMATÓRIA INTESTINAL",
        authors: "Coelho R., Vieira T., Oliveria A., Pereira J., Magro F., Macedo G.",
        url: "src/docs/702.pdf",
    }, {
        id: 17,
        date: 5,
        areaC: 3,
        title: "FACTORES DE RISCO PARA NEOPLASIA INTRA-EPITELIAL NA COLITE ULCEROSA – ESTUDO TRANSVERSAL",
        authors: "Freire P., Figueiredo P., Cardoso R., Donato M.M., Ferreira M., Mendes S., Cipriano M.A., Silva M.R., Ferreira A.M., Vasconcelos H., Portela F., Sofia C.",
        url: "src/docs/620.pdf",
    }, {
        id: 18,
        date: 5,
        areaC: 3,
        title: "AVALIAÇÃO DA ACTIVIDADE NA DOENÇA INFLAMATÓRIA INTESTINAL UTILIZANDO 2 MÉTODOS DE QUANTIFICAÇÃO DA CALPROTECTINA FECAL",
        authors: "Fernandes S., Sousa P., Moura M., Beja Manaças M., Alves J., Correia L., Moura Santos P., Valente A., Gonçalves A. , Baldaia C., Proença H., Velosa J.",
        url: "src/docs/489.pdf",
    }, {
        id: 19,
        date: 5,
        areaC: 3,
        title: "FÍSTULA PERIANAL CRIPTOGLANDULAR OU ASSOCIADA À DOENÇA DE CROHN? CONTRIBUTO DA ULTRASSONOGRAFIA PARA O DIAGNÓSTICO",
        authors: "Dias de Castro F., Boal Carvalho P., Magalhães J., Leite S., Moreira MJ., Cotter J.",
        url: "src/docs/595.pdf",
    }, {
        id: 20,
        date: 5,
        areaC: 3,
        title: "A AMPLITUDE DE DISTRIBUIÇÃO DOS GLÓBULOS VERMELHOS (RDW)  PODE SER CONSIDERADO COMO UM MARCADOR DE ATIVIDADE DA DOENÇA DE CROHN? - UM ESTUDO DE BASE POPULACIONAL",
        authors: "Oliveira A.M., Sousa Cardoso F., Lourenço L., Branco J., Graça Rodrigues C., Santos L., Martins A., Reis J., Ramos Deus J.",
        url: "src/docs/897.pdf",
    }, {
        id: 21,
        date: 5,
        areaC: 6,
        title: "ACALÁSIA OPERADA – DESAFIO CLÍNICO E TERAPÊUTICO",
        authors: "Costa Santos V., Nunes N., Inoue H., Ikeda H., Ávila F., Massinha P., Rego A.C., Pereira J.R., Paz N., Duarte M.A.",
        url: "src/docs/870.pdf",
    }, {
        id: 22,
        date: 5,
        areaC: 6,
        title: "COLOCAÇÃO DE PRÓTESE BILIAR METÁLICA AUTO-EXPANSÍVEL POR CPRE ASSISTIDA POR ENTEROSCOPIA DE MONO-BALÃO: DESCRIÇÃO DE UMA NOVA TÉCNICA",
        authors: "Fernandes C., Pinho R., Proença L., Alberto L., Pinto-Pais T., Ribeiro I., Pereira T., Fraga J., Carvalho J.",
        url: "src/docs/722.pdf",
    }, {
        id: 23,
        date: 5,
        areaC: 6,
        title: "DRENAGEM BILIAR GUIADA POR ECOENDOSCOPIA NA NEOPLASIA AVANÇADA DO PÂNCREAS – 2 CASOS CLÍNICOS",
        authors: "Sofia Vítor, Samuel Fernandes, Rui Palma, Carlos Noronha Ferreira, Luis Carrilho Ribeiro, José Velosa",
        url: "src/docs/467.pdf",
    }, {
        id: 24,
        date: 5,
        areaC: 6,
        title: "COLANGIOSCOPIA DIRETA NA ABORDAGEM DA LITÍASE INTRA-HEPÁTICA",
        authors: "Massinha P., Nunes N., Ávila F., Santos V.C., Rego A.C., Pereira J.R., Paz N., Duarte M.A.",
        url: "src/docs/651.pdf",
    }, {
        id: 25,
        date: 5,
        areaC: 6,
        title: "PANCREATITE AGUDA NECROSANTE INFETADA – DRENAGEM E NECROSECTOMIA ENDOSCÓPICA",
        authors: "Costa Santos V., Nunes N., Ávila F., Massinha P., Rego A.C., Pereira J.R., Paz N., Duarte M.A.",
        url: "src/docs/876.pdf",
    }, {
        id: 26,
        date: 5,
        areaC: 6,
        title: "REMOÇÃO DE PRÓTESE METÁLICA ESOFÁGICA PELA TÉCNICA DA INVAGINAÇÃO/EVERSÃO",
        authors: "Vilas-Boas F., Pereira P., Macedo G",
        url: "src/docs/480.pdf",
    }, {
        id: 27,
        date: 5,
        areaC: 6,
        title: "HEMORRAGIA DIGESTIVA VARICOSA REFRACTÁRIA CONTROLADA COM PRÓTESE METÁLICA AUTO-EXPANSÍVEL",
        authors: "Vilas-Boas F., Marques M., Coelho R., Pereira P., Cardoso H., Macedo G.",
        url: "src/docs/481.pdf",
    }, {
        id: 28,
        date: 5,
        areaC: 6,
        title: "EXTENSA LESÃO ADENOMATOSA DO RETO COM ATINGIMENTO DA LINHA PECTÍNEA RESSECADA POR DISSECÇÃO ENDOSCÓPICA DA SUBMUCOSA",
        authors: "Barreiro P., Rodrigues J., Carmo J., Chagas C.",
        url: "src/docs/786.pdf",
    }, {
        id: 29,
        date: 5,
        areaC: 4,
        title: "ENTEROSCOPIA POR CÁPSULA NA AVALIAÇÃO DA DOENÇA DE CROHN APÓS CIRURGIA DE RESSECÇÃO INTESTINAL",
        authors: "Vilas-Boas F., Cardoso H., Marques M., Velosa M., Rodrigues S., Lopes, S., Magro F. , Macedo G.",
        url: "src/docs/478.pdf",
    }, {
        id: 30,
        date: 5,
        areaC: 4,
        title: "ESTADIAMENTO LOCAL DOS TUMORES DO RECTO POR ECOENDOSCOPIA",
        authors: "Meireles L., Fernandes S., Freitas L., Marques I., Lagos C., Cruz Martins A., Costa Neves B., Carrilho Ribeiro L., Velosa J.",
        url: "src/docs/454.pdf",
    }, {
        id: 31,
        date: 5,
        areaC: 4,
        title: "ENTEROSCOPIA POR CÁPSULA: ACUIDADE DIAGNÓSTICA DO SCORE DE LEWIS NA SUSPEITA DE DOENÇA DE CROHN",
        authors: "Vilas-Boas F., Cardoso H., Marques M., Velosa M., Rodrigues S., Lopes, S., Magro F. , Macedo G.",
        url: "src/docs/669.pdf",
    }, {
        id: 32,
        date: 5,
        areaC: 4,
        title: "DISSECÇÃO ENDOSCÓPICA DA SUBMUCOSA: EXPERIÊNCIA DE 2 ANOS NUM CENTRO HOSPITALAR",
        authors: "Barreiro P., Rodrigues J., Marques S., Carvalho L., Chagas C.",
        url: "src/docs/791.pdf",
    }, {
        id: 33,
        date: 5,
        areaC: 4,
        title: "FACTORES PREDITIVOS DE DOR DURANTE A COLONOSCOPIA SEM SEDAÇÃO",
        authors: "Leitão C., Santos A., Pinto J., Ribeiro H., Pereira B., Caldeira A., Tristan J., Sousa R., Pereira E., Banhudo A.",
        url: "src/docs/827.pdf",
    }, {
        id: 34,
        date: 5,
        areaC: 4,
        title: "PROPOSTA DE UMA CLASSIFICAÇÃO SIMPLIFICADA DE PREPARAÇÃO CÓLICA",
        authors: "Lage J., Brandão C., Ferraz S., Novais A., Dinis-Ribeiro M., Moreira-Dias L.",
        url: "src/docs/838.pdf",
    }, {
        id: 35,
        date: 6,
        areaC: 3,
        title: "PERTURBAÇÃO DO SONO EM DOENTES COM DOENÇA DE CROHN SOB TERAPÊUTICA ANTI-TNF ALFA: PREVALÊNCIA E SUA RELAÇÃO COM QUESTIONÁRIO IBD-CONTROL",
        authors: "Fernandes C., Pais T., Ribeiro I., Silva J., Ponte A., Rodrigues A., Alberto L., Proença L., Silva AP., Pinho R., Carvalho J.",
        url: "src/docs/893.pdf",
    }, {
        id: 36,
        date: 6,
        areaC: 3,
        title: "PREVALÊNCIA E FATORES DE RISCO PARA COLITE ULCEROSA COM CURSO AGRESSIVO",
        authors: "Cardoso R., Campos S., Freire P., Ferreira M., Mendes S., Ferreira A.M., Andrade P., Portela F., Sofia C.",
        url: "src/docs/750.pdf",
    }, {
        id: 37,
        date: 6,
        areaC: 3,
        title: "VALIDAÇÃO DA VERSÃO PORTUGUESA DE UM QUESTIONÁRIO PARA AVALIAÇÃO DA QUALIDADE DOS CUIDADOS DE SAÚDE DO PONTO DE VISTA DO UTENTE COM DOENÇA INFLAMATÓRIA INTESTINAL (QUOTE-IBD)",
        authors: "Fernandes D., Nogueira M., Gonçalves B., Costa S., Machado A., Caetano A., Gonçalves R., Soares J.",
        url: "src/docs/567.pdf",
    }, {
        id: 38,
        date: 6,
        areaC: 3,
        title: "COLONOSCOPIA POR ROTINA APÓS DIVERTICULITE AGUDA NÃO COMPLICADA - É NECESSÁRIA?",
        authors: "Andrade P., Ribeiro A., Macedo G.",
        url: "src/docs/735.pdf",
    }, {
        id: 39,
        date: 6,
        areaC: 3,
        title: "APLICABILIDADE DA QUIMIOTERAPIA PERIOPERATÓRIA NO CANCRO GÁSTRICO: AS DIFICULDADES DA VIDA REAL SÃO SEMELHANTES ÀS DOS ENSAIOS CLÍNICOS",
        authors: "Trabulo D., Moleiro J., Ferreira A., Dionísio R., Cardoso C., Pimenta A., Mão de Ferro S., Serrano M., Ferreira S., Freire J., Luís A., Loureiro A., Casaca R., Bettencourt A., Dias Pereira A.",
        url: "src/docs/771.pdf",
    }, {
        id: 40,
        date: 6,
        areaC: 3,
        title: "TRATAMENTO ENDOSCÓPICO DE FÍSTULAS EM CIRURGIA BARIÁTRICA",
        authors: "Carvalho D., Loureiro R., Russo P., Seves I., Rio-Tinto R.",
        url: "src/docs/780.pdf",
    }, {
        id: 41,
        date: 6,
        areaC: 9,
        title: "CROMOENDOSCOPIA VIRTUAL E MELHORIA NO DIAGNÓSTICO DA ENTEROSCOPIA POR CÁPSULA NA HEMORRAGIA DIGESTIVA DE CAUSA OBSCURA.",
        authors: "Boal Carvalho P, Magalhães J, Dias de Castro F, Cúrdia Gonçalves T, Rosa B, Moreira MJ, Cotter J",
        url: "src/docs/662.pdf",
    }, {
        id: 42,
        date: 6,
        areaC: 9,
        title: "PODERÁ A TERAPÊUTICA EMPÍRICA TRIPLA COM LEVOFLOXACINA REPRESENTAR UMA ALTERNATIVA NOS DOENTES COM FALÊNCIA DO ESQUEMA INICIAL DE ERRADICAÇÃO DO HELICOBACTER PYLORI?",
        authors: "Almeida N., Romãozinho J.M., Donato M.M., Fernandes A., Cardoso O., Luxo C., Cipriano M.A., Marinho C., Sofia C.",
        url: "src/docs/854.pdf",
    }, {
        id: 43,
        date: 6,
        areaC: 9,
        title: "CUSTO-UTILIDADE DA VIGILÂNCIA ENDOSCÓPICA DAS CONDIÇÕES GÁSTRICAS PRÉ-MALIGNAS",
        authors: "Areia M., Dinis-Ribeiro M., Rocha Gonçalves F.",
        url: "src/docs/468.pdf",
    }, {
        id: 44,
        date: 6,
        areaC: 9,
        title: "ATIVAÇÃO DA VIA MEK5-ERK5 AUMENTA A ATIVIDADE DE NF-KB E O POTENCIAL METASTÁTICO DE CÉLULAS DE CANCRO DO CÓLON",
        authors: "Simões A.E.S., Pereira D.M., Gomes S.E., Caridade M., Carvalho T., Castro R.E. , Steer C.J., Thibodeau, S.N., Borralho P.M., Rodrigues C.M.P.",
        url: "src/docs/577.pdf",
    }, {
        id: 45,
        date: 6,
        areaC: 9,
        title: "MIR-143 E MIR-145 AUMENTAM A RESPOSTA AO CETUXIMAB EM CÉLULAS DE CANCRO DO CÓLON COM KRAS MUTADO OU WILD-TYPE: AVALIAÇÃO DA MODULAÇÃO DA CITOTOXICIDADE CELULAR DEPENDENTE DE ANTICORPO ",
        authors: "Gomes SE, Simões AES, Pereira DM, Brito H, Castro RE, Borralho PM, Rodrigues CMP",
        url: "src/docs/581.pdf",
    }, {
        id: 46,
        date: 6,
        areaC: 9,
        title: "INIBIÇÃO DA VIA DE SINALIZAÇÃO MEK5-ERK5 AUMENTA A APOPTOSE INDUZIDA PELO 5-FLUOROURACILO EM CÉLULAS DE CANCRO DO CÓLON",
        authors: "Pereira D.M., Simões A.E.S., Gomes S.E., Castro R.E., Borralho P.M., Rodrigues C.M.P",
        url: "src/docs/580.pdf",
    }, {
        id: 47,
        date: 6,
        areaC: 1,
        title: "ENTERITE ULCERATIVA ESTENOSANTE MULTIFOCAL CRIPTOGÉNICA: CAUSA RARA DE ANEMIA FERROPÉNICA",
        authors: "Andrade P., Marques M., Amil-Dias J., Pardal J., Macedo G.",
        url: "src/docs/739.pdf",
    }, {
        id: 48,
        date: 6,
        areaC: 1,
        title: "SARCOMA DE KAPOSI ISOLADO DO CÓLON EM DOENTE NÃO-VIH COM PANCOLITE ULCEROSA: UM DESAFIO DIAGNÓSTICO E TERAPÊUTICO",
        authors: "Carmo J., Herculano R., Marques S., Costa P., Barreiro P., Bispo M., Matos L., Chagas C.",
        url: "src/docs/989.pdf",
    }, {
        id: 49,
        date: 6,
        areaC: 1,
        title: "UM CASO DE DOR ABDOMINAL, VÓMITOS E ASCITE NUM ADULTO JOVEM ",
        authors: "Lourenço L.C., Oliveira A.M., Rodrigues C.G., Horta D., Reis J., Deus J.R.",
        url: "src/docs/954.pdf",
    }, {
        id: 50,
        date: 6,
        areaC: 5,
        title: "LESÕES HEPÁTICAS FOCAIS: O CONTRIBUTO DA ULTRASSONOGRAFIA COM CONTRASTE",
        authors: "Leitão C., Santos A., Ribeiro H., Pinto J., Caldeira A., Pereira E., Pereira B., Tristan J., Sousa R., Banhudo A.",
        url: "src/docs/817.pdf",
    }, {
        id: 51,
        date: 6,
        areaC: 5,
        title: "TERAPÊUTICA TRIPLA NA HEPATITE C CRÓNICA – RESULTADOS PRELIMINARES DA EXPERIÊNCIA DE UM CENTRO HOSPITALAR",
        authors: "Túlio M., Chapim I., Marques S., Carvalho L., Herculano R., Costa P., Miranda A., Aldir I., Barreiro P., Bispo M., Lebre L., Bana T., Chagas C.",
        url: "src/docs/904.pdf",
    }, {
        id: 52,
        date: 6,
        areaC: 5,
        title: "CARACTERIZAÇÃO DA HEPATITE C GENÓTIPO 1 – A EXPERIÊNCIA DE UM CENTRO",
        authors: "Rodrigues-Pinto E., Cardoso H., Coelho R., Andrade P., Horta e Vale A.M., Sarmento J.A., Pereira P., Lopes S., Marques M., Gonçalves R., Rodrigues S., Araújo F., Macedo G.",
        url: "src/docs/574.pdf",
    }, {
        id: 53,
        date: 6,
        areaC: 5,
        title: "ESTIMATIVA DO CUSTO DE UM INTERNAMENTO HOSPITALAR POR CIRROSE HEPÁTICA NUM SERVIÇO DE GASTRENTEROLOGIA",
        authors: "Silva M.J., Costa M.N., Roque A., Leão R., Calinas F.",
        url: "src/docs/861.pdf",
    }, {
        id: 54,
        date: 6,
        areaC: 5,
        title: "AVALIAÇÃO DA FIBROSE HEPÁTICA NA HEPATITE B CRÓNICA: ACUIDADE DIAGNÓSTICA DE QUATRO TESTES NÃO INVASIVOS",
        authors: "Magalhães J., Dias de Castro F., Boal Carvalho P., Leite S., Moreira MJ., Cotter J.",
        url: "src/docs/476.pdf",
    }, {
        id: 55,
        date: 6,
        areaC: 5,
        title: "INSUFICIÊNCIA HEPÁTICA AGUDA DE CAUSA HIPÓXICA – UMA ENTIDADE FREQUENTEMENTE NEGLIGENCIADA",
        authors: "Carvalhana S., Trabulo D., Gonçalves A., Valente A., Palma R., Alexandrino P., Velosa J.",
        url: "src/docs/774.pdf",
    }, {
        id: 56,
        date: 6,
        areaC: 7,
        title: "EXPOSIÇÃO OCUPACIONAL A RADIAÇÃO EM PROFISSIONAIS DE SAÚDE DURANTE A CPRE",
        authors: "Alves A.R., Gomes D., Mendes P., Laranjeiro T., Paulo G., Santos J., Casela A., Perdigoto D., Almeida N., Mendes S., Mesquita R., Camacho E., Portela F., Sofia C.",
        url: "src/docs/937.pdf",
    }, {
        id: 57,
        date: 6,
        areaC: 7,
        title: "ACUIDADE DIAGNÓSTICA DA PUNÇÃO GUIADA POR ECOENDOSCOPIA EM TUMORES SÓLIDOS DO PÂNCREAS: COMPARAÇÃO CITOLOGIA VERSUS “CELL-BLOCK”",
        authors: "Elvas L., Brito D., Carvalho R., Areia M., Alves S., Saraiva S., Pontes J.M., Cadime A.T.",
        url: "src/docs/752.pdf",
    }, {
        id: 58,
        date: 6,
        areaC: 7,
        title: "PRÓTESES METÁLICAS AUTO-EXPANSÍVEIS NO TRATAMENTO DE COLECÇÕES PANCREÁTICAS ORGANIZADAS",
        authors: "Lopes S., Vilas-Boas F., Baldaque-Silva F., Pereira P., Ribeiro A., Macedo G.",
        url: "src/docs/485.pdf",
    }, {
        id: 59,
        date: 6,
        areaC: 7,
        title: "TUMORES QUÍSTICOS DO PÂNCREAS OPERADOS: ACUIDADE DOS CRITÉRIOS REVISTOS DE SENDAI NA AVALIAÇÃO DE MALIGNIDADE",
        authors: "Faias S., Pereira da Silva J., Fonseca R., André S., Dias Pereira A.",
        url: "src/docs/820.pdf",
    }, {
        id: 60,
        date: 6,
        areaC: 7,
        title: "COLANGIOPANCREATOGRAFIA RETRÓGRADA ENDOSCÓPICA NA SUSPEITA DE COLEDOCOLITÍASE – DAS GUIDELINES À PRÁTICA CLÍNICA",
        authors: "Magalhães J., Rosa B., Cotter J.",
        url: "src/docs/593.pdf",
    }, {
        id: 61,
        date: 6,
        areaC: 7,
        title: "PUNÇÃO ASPIRATIVA DE LESÕES SÓLIDAS DO PÂNCREAS GUIADA POR ECOENDOSCOPIA – IMPACTO NA DECISÃO CLÍNICA",
        authors: "Lourenço L.C., Oliveira A.M., Rodrigues C.G., Horta D., Reis J., Pontes  J.M., Deus  J.R.",
        url: "src/docs/947.pdf",
    }, {
        id: 62,
        date: 6,
        areaC: 2,
        title: "INFLIXIMAB: INDUTOR DO AUMENTO DO NÚMERO DE MONÓCITOS CD16+ CIRCULANTES E MODIFICADOR DA RESPOSTA À INFEÇÃO BACTERIANA",
        authors: "Coelho R, Nazareth N., Appelberg R., Gracio D., Sarmento A., Magro F., Macedo G.",
        url: "src/docs/705.pdf",
    }, {
        id: 63,
        date: 6,
        areaC: 2,
        title: "DESENVOLVIMENTO TUMORAL PRIMÁRIO E SECUNDÁRIO DE CARCINOMA COLORRETAL EM MODELO ORTOTÓPICO – QUAL O PAPEL DO MICROAMBIENTE TUMORAL?",
        authors: "Caetano Oliveira R., Abrantes A.M., Tavares-Silva E., Pires A.S., Mamede A.C. , Gomes M.A., Tralhão J.G., Botelho M.F.",
        url: "src/docs/985.pdf",
    }, {
        id: 64,
        date: 6,
        areaC: 2,
        title: "INIBIÇÃO DA EXPRESSÃO DE KRAS MUTADO EM CÉLULAS HUMANAS  DE CANCRO DO CÓLON",
        authors: "Brito H., Lavrado J., Moreira R., Paulo A., Rodrigues C.M.P., Borralho P.M.",
        url: "src/docs/579.pdf",
    }, {
        id: 65,
        date: 6,
        areaC: 2,
        title: "BUTIRATO E IRINOTECANO: UMA NOVA ABORDAGEM PARA O TRATAMENTO DO CANCRO COLORRETAL",
        authors: "Encarnação J.C., Pires A.S., Gonçalves T.J., Casalta-Lopes J.E., Gonçalves AC, Abrantes A.M., Sarmento-Ribeiro A.B., Botelho M.F.",
        url: "src/docs/616.pdf",
    }, {
        id: 66,
        date: 6,
        areaC: 2,
        title: "DETERMINAÇÃO DO DANO NO ADN, DANO OXIDATIVO E ÍNDICE DE STRESS OXIDATIVO NOS DOENTES COM DOENÇA INFLAMATÓRIA INTESTINAL",
        authors: "Coelho R., Pereira C., Magro F., Macedo G.",
        url: "src/docs/693.pdf",
    }, {
        id: 67,
        date: 6,
        areaC: 2,
        title: "GRANDES DELECÇÕES GERMINAIS EPCAM-MSH2 EM DOENTES COM SÍNDROMA DE LYNCH: INACTIVAÇÃO SOMÁTICA ASSOCIADA A UM FENÓTIPO AGRESSIVO  ",
        authors: "Francisco I., Albuquerque C., Filipe B., Silva P., Lage P., Claro I., Ferreira S., Rosa I., Fonseca R., Rodrigues P., Chaves P., Dias Pereira A.",
        url: "src/docs/926.pdf",
    }, {
        id: 68,
        date: 6,
        areaC: 4,
        title: "FATORES PREDITIVOS DE NÃO RECUPERAÇÃO DE PÓLIPOS CÓLICOS RESSECADOS ENDOSCOPICAMENTE",
        authors: "Fernandes C., Pinho R., Leite S., Proença L., Rodrigues A., Alberto L., Fernandes S., Silva AP., Freitas T., Pais T., Ribeiro I., Silva J., Ponte A., Carvalho J.",
        url: "src/docs/609.pdf",
    }, {
        id: 69,
        date: 6,
        areaC: 4,
        title: "VALIDAÇÃO DO ÍNDICE DE GAY NA SELEÇÃO DA VIA DE ABORDAGEM POR ENTEROSCOPIA DE MONO-BALÃO APÓS ACHADOS POSITIVOS EM CÁPSULA ENDOSCÓPICA",
        authors: "Fernandes C., Pinho R., Rodrigues A., Pais T., Ribeiro I., Silva J., Ponte A., Carvalho J.",
        url: "src/docs/718.pdf",
    }, {
        id: 70,
        date: 6,
        areaC: 4,
        title: "ACUIDADE DA ECOENDOSCOPIA PARA SELEÇÃO DE TRATAMENTO NEOADJUVANTE NO CANCRO GÁSTRICO",
        authors: "Gonçalves BM, Bastos P, Soares JB, Fernandes D, Cunha J*, Couto E*, Rolanda C, Gonçalves R",
        url: "src/docs/536.pdf",
    }, {
        id: 71,
        date: 6,
        areaC: 4,
        title: "DESNUTRIÇÃO E EVOLUÇÃO CLÍNICA DE 234 DOENTES COM NEOPLASIAS CERVICO-FACIAIS SUBMETIDOS A GASTROSTOMIA ENDOSCÓPICA ",
        authors: "Fonseca J, Pereira M, Carrapito T, Santos CA",
        url: "src/docs/550.pdf",
    }, {
        id: 72,
        date: 6,
        areaC: 4,
        title: "GASTROSTOMIA ENDOSCÓPICA PERCUTÂNEA TRANS-NASAL (PEG-TN) EM DOENTES COM TUMORES DA CABEÇA E PESCOÇO: ABORDAGEM CONJUNTA POR GASTRO E PNEUMOLOGIA ",
        authors: "Faias S., Duro da Costa, Dionísio J., Costa P. , Rosa I., Ferreira S., Mão de Ferro S., Pereira da Silva J., Dias Pereira A.",
        url: "src/docs/801.pdf",
    }, {
        id: 73,
        date: 6,
        areaC: 4,
        title: "OS DOENTES COM TUMORES DA CABEÇA E PESCOÇO SUBMETIDOS A QUIMIORADIOTERAPIA DEFINITIVA TÊM DISFAGIA PROLONGADA E NECESSITAM DE PEG PROFILÁTICA",
        authors: "Rodrigues R.V., Faias S., Moleiro J., Serrano M., Femenia M, Severiano S., Machado V., Dias Pereira A.",
        url: "src/docs/751.pdf",
    }, {
        id: 74,
        date: 7,
        areaC: 1,
        title: "PANCREATITE AUTO-IMUNE TIPO 1 (PAI1) E TIPO 2 (PAI2): PARTICULARIDADES DA CLÍNICA E DIAGNÓSTICO",
        authors: "Palmela C., Torres J., Fidalgo C., Espírito Santo J., Noronha C., Strecht J., Oliveira H., Santos A. A., Cravo M.",
        url: "src/docs/957.pdf",
    }, {
        id: 75,
        date: 7,
        areaC: 1,
        title: "ENTEROPATIA SPRUELIKE ASSOCIADA AO OLMESARTAN",
        authors: "Coelho R., Albuquerque A., Cardoso H.1, Rodrigues-Pinto E., Vilas-Boas F., Carneiro F., Macedo G.",
        url: "src/docs/628.pdf",
    }, {
        id: 76,
        date: 7,
        areaC: 1,
        title: "ALTERAÇÃO DAS PROVAS HEPÁTICAS EM DOENTE COM INFECÇÃO POR VÍRUS DA IMUNODEFICIÊNCIA HUMANA – DESAFIO DIAGNÓSTICO",
        authors: "Barosa R¹, , Roque Ramos L¹, , Figueiredo P¹,, Meira T¹, , Águas MJ², , Fonseca C¹, , Freitas J¹",
        url: "src/docs/512.pdf",
    }, {
        id: 77,
        date: 7,
        areaC: 1,
        title: "DUPLA DERIVAÇÃO BILIO-DIGESTIVA POR VIA ENDOSCÓPICA: EFICÁCIA CLÍNICA E REVISÃO ENDOSCÓPICA",
        authors: "Barosa R, Roque Ramos L, Figueiredo P, Meira T, Águas MJ, Fonseca C, Freitas J",
        url: "src/docs/543.pdf",
    }, {
        id: 78,
        date: 7,
        areaC: 1,
        title: "TRATAMENTO AGUDO DA OCLUSÃO COLORECTAL MALIGNA: PRÓTESE COMO PONTE ATÉ A CIRURGIA OU TRATAMENTO PALIATIVO VERSUS CIRURGIA DE URGÊNCIA",
        authors: "Fernandes D., Domingues S., Gonçalves B., Costa S., Soares J., Bastos P., Ferreira A., Gonçalves R., Rolanda C.",
        url: "src/docs/566.pdf",
    }, {
        id: 79,
        date: 7,
        areaC: 1,
        title: "PÓLIPOS MALIGNOS DO CÓLON: EXPERIÊNCIA DE UM CENTRO ",
        authors: "Elvas L., Carvalho R., Areia M., Alves S., Brito D., Saraiva S., Cadime A.T.",
        url: "src/docs/754.pdf",
    }, {
        id: 80,
        date: 7,
        areaC: 9,
        title: "AIMS65: AVALIAÇÃO PROSPETIVA DE UMA ESCALA PROGNÓSTICA NA HEMORRAGIA DIGESTIVA ALTA",
        authors: "Cardoso R., Leal T., Amaro P., Ferreira M., Portela F., Romãozinho J.M., Sofia C.",
        url: "src/docs/863.pdf",
    }, {
        id: 81,
        date: 7,
        areaC: 9,
        title: "PODERÁ O VALOR BASAL DO TESTE RESPIRATÓRIO DA UREIA CONSTITUIR UM FATOR PREDITIVO DO SUCESSO DA ERRADICAÇÃO DO HELICOBACTER PYLORI?",
        authors: "Alves A.R., Almeida N., Elvas L., Casela A., Fernandes A., Donato M.M., Calhau C., Romãozinho J.M., Sofia C.",
        url: "src/docs/665.pdf",
    }, {
        id: 82,
        date: 7,
        areaC: 9,
        title: "MUTAÇÕES DO GENE NOD2 E INFEÇÃO POR HELICOBACTER PYLORI – INFLUÊNCIA NA PREVALÊNCIA E NO PADRÃO DE RESISTÊNCIA",
        authors: "Fernandes A., Almeida N., Freire P., Donato M.M., Calhau C., Cardoso R., Alves R., Casela A., Oliveira A., Romãozinho J.M., Sofia C.",
        url: "src/docs/832.pdf",
    }, {
        id: 83,
        date: 7,
        areaC: 6,
        title: "SCHOENDRA STENT RETRIEVER NA DRENAGEM DE PSEUDOQUISTO PANCREÁTICO",
        authors: "Costa Santos V., Nunes N., Ávila F., Massinha P., Rego A.C., Pereira J.R., Paz N., Duarte M.A.",
        url: "src/docs/878.pdf",
    }, {
        id: 84,
        date: 7,
        areaC: 6,
        title: "REMOÇÃO ENDOSCÓPICA DE BANDA GÁSTRICA MIGRADA",
        authors: "Mocanu I., Pires S., Godinho R., Gonçalves L., Medeiros I.",
        url: "src/docs/527.pdf",
    }, {
        id: 85,
        date: 7,
        areaC: 6,
        title: "REMOÇÃO ENDOSCÓPICA DE BANDA GÁSTRICA MIGRADA: EXPERIÊNCIA DE UM CENTRO HOSPITALAR",
        authors: "Marques S., Rio-Tinto R., Carmo J., Costa P., Bispo M., Alves I., Chagas C.",
        url: "src/docs/531.pdf",
    }, {
        id: 86,
        date: 7,
        areaC: 6,
        title: "TERAPÊUTICA HEMOSTÁTICA COM HEMOSPRAY NUM CASO DE HEMORRAGIA DIGESTIVA BAIXA",
        authors: "Lage J., Silva R., Moreira-Dias L.",
        url: "src/docs/828.pdf",
    }, {
        id: 87,
        date: 7,
        areaC: 6,
        title: "MIOTOMIA DO CRICOFARÍNGEO COM ENDOSCÓPIO FLEXÍVEL",
        authors: "Mocanu I., Pires S., Godinho R., Gonçalves L., Medeiros I.",
        url: "src/docs/529.pdf",
    }, {
        id: 88,
        date: 7,
        areaC: 6,
        title: "TUMOR NEUROENDÓCRINO DO RETO EXCISADO POR DISSECÇÃO ENDOSCÓPICA DA SUBMUCOSA",
        authors: "Barreiro P., Rodrigues J., Costa P., Chagas C.",
        url: "src/docs/805.pdf",
    }, {
        id: 89,
        date: 7,
        areaC: 6,
        title: "SÍNDROMA DE BOERHAAVE EM IDADE JOVEM - APRESENTAÇÃO INCOMUM, TERAPÊUTICA PROCOCE",
        authors: "Fernandes S., Carvalhana S., Noronha Ferreira C. , Paulo Freire J., Carrilho Ribeiro L., Velosa J.",
        url: "src/docs/822.pdf",
    }, {
        id: 90,
        date: 7,
        areaC: 6,
        title: "METÁSTASE DE MELANOMA OCULAR DIAGNOSTICADA POR PUNÇÃO DIRIGIDA POR ECOENDOSCOPIA",
        authors: "Vilas-Boas F., Lopes S., Lopes J., Macedo G.",
        url: "src/docs/484.pdf",
    }, {
        id: 91,
        date: 7,
        areaC: 6,
        title: "POLIPOSE LINFOMATOSA MÚLTIPLA, VARIANTE BLASTÓIDE, DIAGNOSTICADA POR COLONOSCOPIA VIRTUAL E COLONOSCOPIA",
        authors: "Rodrigues-Pinto E., Ribeiro A., Fosenca E., Macedo G.",
        url: "src/docs/583.pdf",
    }, {
        id: 92,
        date: 7,
        areaC: 6,
        title: "ENCERRAMENTO DE FÍSTULA ENTERO-VESICAL COM OVER-THE-SCOPE CLIP (OTSC)",
        authors: "Fernandes C., Pinho R., Proença L., Pais T., Ribeiro I., Carvalho J.",
        url: "src/docs/611.pdf",
    }, ]);
var projectX = window.projectX;
var areasC = window.areasC;
